-- MySQL Script generated by MySQL Workbench
-- Tue 22 Oct 2019 10:07:36 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `null_bank` DEFAULT CHARACTER SET utf8 ;
USE `null_bank` ;

-- -----------------------------------------------------
-- Table `null_bank`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `null_bank`.`cliente` (
  `cpf` INT NOT NULL,
  `nome_completo` VARCHAR(150) NOT NULL,
  `RG` INT NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `tipo_logradouro` VARCHAR(45) NOT NULL,
  `nome_logradouro` VARCHAR(150) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `CEP` INT NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nro_conta` INT NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `null_bank`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `null_bank`.`telefone` (
  `numero_ctt` INT(11) NOT NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`numero_ctt`, `cliente_cpf`),
  INDEX `fk_telefone_cliente_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_telefone_cliente`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `null_bank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `null_bank`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `null_bank`.`email` (
  `email` VARCHAR(45) NOT NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`email`, `cliente_cpf`),
  INDEX `fk_email_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `null_bank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `null_bank`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `null_bank`.`dependente` (
  `nome_completo` INT NOT NULL,
  `cliente_cpf` INT NOT NULL,
  `data_nasc` DATE NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`nome_completo`, `cliente_cpf`),
  INDEX `fk_dependente_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_dependente_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `null_bank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
