-- MySQL Script generated by MySQL Workbench
-- Tue 19 Nov 2019 02:41:18 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `null_bank` DEFAULT CHARACTER SET utf8 ;
USE `null_bank` ;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome_completo` VARCHAR(150) NOT NULL,
  `RG` VARCHAR(15) NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `UF_emissor` VARCHAR(2) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `idade` INT NULL,
  `tipo_logradouro` VARCHAR(45) NOT NULL,
  `nome_logradouro` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telefone` (
  `numero_ctt` VARCHAR(11) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`numero_ctt`, `cliente_cpf`),
  INDEX `fk_telefone_cliente_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_telefone_cliente`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email` (
  `email` VARCHAR(45) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`email`, `cliente_cpf`),
  INDEX `fk_email_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia` (
  `id_agencia` VARCHAR(4) NOT NULL,
  `nome_agencia` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `montante_salarial` FLOAT NULL,
  PRIMARY KEY (`id_agencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome_completo` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `salario` FLOAT NOT NULL,
  `data_nasc` DATE NOT NULL,
  `idade` INT NOT NULL,
  `tipo_logradouro` VARCHAR(45) NOT NULL,
  `nome_logradouro` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionario_agencia1_idx` (`agencia_id_agencia` ASC),
  CONSTRAINT `fk_funcionario_agencia1`
    FOREIGN KEY (`agencia_id_agencia`)
    REFERENCES `agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dependente` (
  `nome_completo` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NULL,
  `idade` INT NULL,
  `parentesco` VARCHAR(45) NULL,
  `funcionario_matricula` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`nome_completo`, `funcionario_matricula`),
  INDEX `fk_dependente_funcionario1_idx` (`funcionario_matricula` ASC),
  CONSTRAINT `fk_dependente_funcionario1`
    FOREIGN KEY (`funcionario_matricula`)
    REFERENCES `funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conta` (
  `id_conta` VARCHAR(8) NOT NULL,
  `saldo` FLOAT NULL,
  `senha` VARCHAR(10) NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `gerente_matricula` VARCHAR(5) NOT NULL,
  `agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_conta`, `agencia_id_agencia`),
  INDEX `fk_conta_agencia1_idx` (`agencia_id_agencia` ASC),
  INDEX `fk_conta_cliente1_idx` (`cliente_cpf` ASC),
  INDEX `fk_conta_funcionario1_idx` (`gerente_matricula` ASC),
  CONSTRAINT `fk_conta_agencia1`
    FOREIGN KEY (`agencia_id_agencia`)
    REFERENCES `agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_funcionario1`
    FOREIGN KEY (`gerente_matricula`)
    REFERENCES `funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poupanca` (
  `taxa_de_juros` FLOAT NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_poupanca_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especial` (
  `limite_credito` FLOAT NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_especial_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corrente` (
  `aniver_contrato` DATE NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_corrente_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trasnsacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trasnsacao` (
  `id_trasnsacao` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `data_hora` DATE NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_trasnsacao`, `conta_id_conta`, `conta_agencia_id_agencia`),
  INDEX `fk_trasnsacao_conta1_idx` (`conta_id_conta` ASC, `conta_agencia_id_agencia` ASC),
  CONSTRAINT `fk_trasnsacao_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste` (
  `idteste` INT NOT NULL,
  PRIMARY KEY (`idteste`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
